version: "3"

services:
  # Database
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ivory
      MYSQL_USER: usr
      MYSQL_PASSWORD: password
      UPLOAD_LIMIT: 300M
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  #
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_DATABASE: ivory
      MYSQL_USER: usr
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 300M
    networks:
      - mysql-phpmyadmin
  nginx:
    build: ./docker/nginx/
    ports:
      - 80:80

    volumes:
      - ./:/var/www/html/
    networks:
      - mysql-phpmyadmin

  php:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db:
    driver: local

